branch-defaults:
  default:
    environment: null
  master:
    environment: cvchecker
global:
  application_name: service-penilaian-cv-master
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
