/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:de3dbefa-87a0-4be3-9165-acb9a1b42d4e",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_mopJbpYYI",
    "aws_user_pools_web_client_id": "6cpobur390u5fv3lv6peeob7ms",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME",
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 7,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://yksucwd5ung3tddtje7xzkovy4.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ia52gdrvfnapze4ndci7vct5se",
    "aws_user_files_s3_bucket": "cvchecker14201-staging",
    "aws_user_files_s3_bucket_region": "ap-southeast-1",
    "predictions": {
        "identify": {
            "identifyText": {
                "proxy": false,
                "region": "ap-southeast-1",
                "defaults": {
                    "format": "ALL"
                }
            }
        },
        "convert": {
            "speechGenerator": {
                "region": "ap-southeast-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Joanna",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
